# .github/workflows/publish-nuget.yml
name: Publish NuGet Package

on:
  push:
    tags:
      - '*.*.*'        # ← only fires when you push a tag with semver format

jobs:
  publish:
    runs-on: ubuntu-latest
    
    env:
      PROJECT_PATH: './src/urldetector'   # adjust to the folder that contains your .csproj
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # 👇 pull every branch & tag so GitVersion can see full history
          fetch-depth: 0
          # 👇 (optional) ensure it checks out the exact tag that triggered the run
          ref: ${{ github.ref }}
          
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles(format('{0}/**/*.csproj', env.PROJECT_PATH)) }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            ${{ runner.os }}-nuget-${{ hashFiles(format('{0}/**/*.csproj', env.PROJECT_PATH)) }}

      - name: Restore dependencies
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet restore

      - name: Build in Release
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Pack NuGet package
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet pack --configuration Release --no-build --output nupkg

      - name: Push package to nuget.org
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          dotnet nuget push nupkg/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
